"""Add upload metadata

Revision ID: d56af1e21443
Revises: adb1d1dd8461
Create Date: 2026-07-15 00:46:46.091732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56af1e21443'
down_revision: Union[str, Sequence[str], None] = 'adb1d1dd8461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'mime_type')
    op.drop_column('invoices', 'file_size')
    op.drop_column('invoices', 'file_path')
    # ### end Alembic commands ###
